package com.luv2code.springboot.cruddemo.repository;

//if using JPA, no need for an entity manager

////@Repository
//public class EmployeeRepo implements iEmployeeRepo {
//	//define field for entity manager
//	private EntityManager entityManager;  //bean autogenerated by spring boot behind the scenes
//
////	set up constructor injection
//	@Autowired
//	public EmployeeRepo(EntityManager eManager) { //eManager auto injected by Spring boot, using constructor injection)
//		this.entityManager = eManager;
//	}
//
//	@Override
//	public List<Employee> findAll() {
////		get the current hibernate session
//		Session currentSession = entityManager.unwrap(Session.class);
//
////		create a query
//		Query<Employee> query = currentSession.createQuery("from Employee", Employee.class);
//
////		execute query and get result list
//		List<Employee> employees = query.getResultList();
//
////		return the results
//		return employees;
//	}
//
//}
